# Regression with Gradient Descent


### Let us start by using a data set of house prices to try and predict the values. 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('kc_house_train_data.csv')

In [3]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

We inspect the data more by looking at its shape. As we can see below, the data has 17384 entries and 21 features. 

In [10]:
df.shape

(17384, 21)

Let us start first by building a numpy array for only 1 feature which will be the sqft_living and the price as the output

In [33]:
df_slice = df[['price', 'sqft_lot']]

In [62]:
sqft_matrix = df_slice.to_numpy()

In [90]:
price = [item[0] for item in sqft_matrix]
sqft_matrix[:,0] = 1
sqft_lot = sqft_matrix

In [91]:
price

[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0

In [92]:
sqft_lot

array([[1.000e+00, 5.650e+03],
       [1.000e+00, 7.242e+03],
       [1.000e+00, 1.000e+04],
       ...,
       [1.000e+00, 1.131e+03],
       [1.000e+00, 2.388e+03],
       [1.000e+00, 1.076e+03]])

### First, we need to create a function for the cost. 

In [93]:
def cost_function(X, y, theta):
    m = len(y)
    J = 0
    
    h = np.dot(X, np.transpose(theta))
    J = (1/2*m)*(np.sum(h - y))
    return J

In [94]:
cost = cost_function(sqft_lot, price, [1,1])

In [95]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Gradient Descent

In [122]:
def gradient_descent(X, y, theta, step, iters):
    m = len(y)
    J_array = np.zeros(iters)
    
    for i in range(iters):
        scalar = (1/m) * step
        h = np.dot(X, np.transpose(theta))
        theta = theta - (scalar * np.dot(np.transpose(X), h-y))
        J_array[i] = cost_function(X, y ,theta) 
        print(J_array[i])
    return theta, J_array

In [120]:
features, history = gradient_descent(sqft_lot, price, [0, 0], 1, 15)

3.4415803675053116e+16
-6.699167551074089e+25
1.304018534064841e+35
-2.538321850021494e+44
4.94094036701489e+53
-9.617729016590148e+62
1.8721276632700525e+72
-3.6441679543426776e+81
7.093512018439017e+90
-1.3807791898223568e+100
2.68773939635336e+109
-5.23178732411183e+118
1.018387372000187e+128
-1.9823298907233933e+137
3.85868079642161e+146


In [124]:
features

array([1.31191742e+129, 1.69209671e+134])